CREATE DATABASE pizzaria;
USE pizzaria;

CREATE TABLE bordas(
	id INTEGER PRIMARY KEY NOT NULL AUTO_INCREMENT,
    nome VARCHAR(45)
);

CREATE TABLE massas(
	id INTEGER PRIMARY KEY NOT NULL AUTO_INCREMENT,
    nome VARCHAR(45)
);

CREATE TABLE sabores(
	id INTEGER PRIMARY KEY NOT NULL AUTO_INCREMENT,
    nome VARCHAR(45)
);

CREATE TABLE pizzas(
	id INTEGER PRIMARY KEY NOT NULL AUTO_INCREMENT,
    id_bordas INTEGER,
    id_massas INTEGER,
    FOREIGN KEY (id_bordas) REFERENCES bordas(id),
    FOREIGN KEY (id_massas) REFERENCES massas(id)
);

CREATE TABLE pizza_sabor(
	id INTEGER PRIMARY KEY NOT NULL AUTO_INCREMENT,
    id_pizza INTEGER NOT NULL,
    id_sabor INTEGER NOT NULL,
	FOREIGN KEY (id_pizza) REFERENCES pizzas(id),
    FOREIGN KEY (id_sabor) REFERENCES sabores(id)
);

CREATE TABLE status(
	id INTEGER PRIMARY KEY NOT NULL AUTO_INCREMENT,
    nome VARCHAR(50)
);

CREATE TABLE pedido(
	id INTEGER PRIMARY KEY NOT NULL AUTO_INCREMENT,
    id_pizza INTEGER NOT NULL,
    id_status INTEGER NOT NULL,
    FOREIGN KEY (id_pizza) REFERENCES pizzas(id),
    FOREIGN KEY (id_status) REFERENCES status(id)
);